name: 编译padavan_natmap

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/heiher/natmap/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lmq8267/natmap_padavan/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码
        uses: actions/checkout@v3
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - 
        name: 克隆源码
        shell: bash
        run: |
          git clone --recursive https://github.com/heiher/natmap -b ${{ needs.check.outputs.ver }} /opt/natmap
          cd /opt/natmap/third-part
          #下载编译工具链
          wget -q -c https://github.com/lmq8267/n2n-2.8.x/releases/download/toolchain/host.zip -P /opt/gcc/
          unzip -q /opt/gcc/host.zip -d /opt/gcc/
          sudo chmod 777 -R /opt/gcc
      - name: 安装 UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true
      - name: 编译
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          export PATH=$PATH:/opt/gcc/host/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gcc/host/lib
          export CC=mipsel-linux-gcc
          export LD=mipsel-linux-ld
          export AR=mipsel-linux-ar
          export RANLIB=mipsel-linux-ranlib
          cd /opt/natmap
          make CROSS_PREFIX=/opt/gcc/host/bin/mipsel-linux-
          cd ./bin
          /opt/gcc/host/bin/mipsel-linux-strip natmap
          cp -f natmap natmap_upx
          upx --lzma --best natmap_upx
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           这是padavan的uclibc动态库版本
           静态库的请下载作者的natmap-linux-mips32el

           natmap 为原版
           natmap_upx 为压缩版本
           
           **[官方更新说明](https://github.com/heiher/natmap/releases)**
          tag_name: ${{ needs.check.outputs.ver }}
          files: /opt/natmap/bin/* 
  keepalive-workflow:
    # github超过60天未提交将自动停止工作流
    name: 工作流保活 
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        #with:
          #use_api: true
